global:
  resolve_timeout: 1h
route:
  group_by: ['alertname']
  receiver: 'wechat'
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 10m

receivers:
- name: 'wechat'
  wechat_configs:
  - corp_id: '企业ID'
    to_party: '组ID'
    agent_id: '应用ID'
    api_secret: '应用密钥'
    #是否发送恢复信息
    send_resolved: true
#告警模板
templates: 
- '/etc/alertmanager/configmaps/alertmanager-temp/temp.yaml'