---
# Source: prometheus-mysql-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter-prometheus-mysql-exporter
  labels:
    app: prometheus-mysql-exporter
    chart: prometheus-mysql-exporter-0.3.2
    release: mysql-exporter
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 9104
      targetPort: 9104
      protocol: TCP
      name: mysql-exporter
  selector:
    app: prometheus-mysql-exporter
    release: mysql-exporter

---
# Source: prometheus-mysql-exporter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter-prometheus-mysql-exporter
  labels:
    app: prometheus-mysql-exporter
    chart: prometheus-mysql-exporter-0.3.2
    release: mysql-exporter
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-mysql-exporter
      release: mysql-exporter
  template:
    metadata:
      labels:
        app: prometheus-mysql-exporter
        release: mysql-exporter
        
    spec:
      containers:
        - name: prometheus-mysql-exporter
          image: "prom/mysqld-exporter:v0.11.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: DATA_SOURCE_NAME
              value: "root:mysql@(mysql-svc:3306)/"
          ports:
            - containerPort: 9104
          livenessProbe:
            httpGet:
              path: /
              port: 9104
          readinessProbe:
            httpGet:
              path: /
              port: 9104
          resources:
            {}
            

---
